eUseControl.Web/Models/Order.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eUseControl.Web.Models
{
     public class Order
     {
               public int SubscriptionId { get; set; }
               public int TrainerId { get; set; }

               public int SubscriptionDurationId { get; set; }



     }
}

eUseControl.Web/Controllers/OrderController.cs
using System;
using System.Web.Mvc;
using eUseControl.BusinessLogic.BL;
using eUseControl.BusinessLogic.Interfaces;
using eUseControl.Domain.Entities.Order;
using eUseControl.Domain.Entities.Subscription;
using eUseControl.Web.Models;

namespace eUseControl.Web.Controllers
{
     public class OrderController : BaseController
     {
          private readonly ISubscription _subscription;
          private readonly ITrainer _trainers;
          private readonly ISubscriptionDuration _details;
          private readonly IOrder _order;
          public OrderController()
          {
               var bl = new BussinesLogic();
               _subscription = bl.GetSubscriptionBl();
               _trainers = bl.GetTrainerBl();
               _details =bl.GetsSubscriptionDurationBl();
               _order = bl.GetOrderBl();
          }
          public ActionResult Index()
          {
               GetUserData();

               var subscriptions = _subscription.GetSubscriptionList();
               var trainers = _trainers.GetTrainersList();
               var details = _details.GetAllSubscriptionDuration();
               OrderModel data = new OrderModel();
               foreach (var item in subscriptions)
                    data.OrderData.Subscriptions.Add(new SubscriptionData
                    {
                         Id = item.Id,
                         Name = item.Name,
                         Description = item.Description,
                         Price = item.Price,
                         ImageUrl = item.ImageUrl
                    });
               foreach (var item in trainers)
                    data.OrderData.Trainers.Add(new Trainer
                    {
                         Id = item.Id,
                         Name = item.Name,
                         ImageUrl = item.ImageUrl,
                         Age = item.Age,
                         Bio = item.Bio,
                         Number = item.Number,
                         Specialization = item.Specialization,
                         Availability = item.Availability,
                         Price = item.Price
                    });
               foreach (var item in details)
                    data.OrderData.SubscriptionDurations.Add(new SubscriptionDuration()
                    {

                         Id = item.Id,
                         Name = item.Name,
                         Months = item.Months,
                         Discount = item.Discount
                    });

               return View(data);

          }


          [HttpPost]
          public ActionResult Index(OrderModel order)
          {
               GetUserData();
               var data = new OrderDbTable()
               {
                    UserId = ViewBag.UserId,
                    UserName = ViewBag.Username,
                    SubscriptionId = order.Orders.SubscriptionId,
                    TrainerId = order.Orders.TrainerId,
                    SubscriptionDurationId = order.Orders.SubscriptionDurationId,
                    PurchaseDate = DateTime.Now,
                    IsValid = true

               };
               _order.CreateOrder(data);
               return RedirectToAction("UserProfile", "Profile");
          }
     }
}

eUseControl.Web/Controllers/TrainersController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using eUseControl.BusinessLogic.BL;
using eUseControl.BusinessLogic.Interfaces;
using eUseControl.Domain.Entities.Trainer;
using eUseControl.Web.Models;

namespace eUseControl.Web.Controllers
{
     public class TrainersController : BaseController
     {
          private readonly ITrainer _trainers;
          private readonly ISession _sessions;

          public TrainersController()
          {
               BussinesLogic bl = new BussinesLogic();
               _trainers = bl.GetTrainerBl();
               _sessions = bl.GetSessionBl();
          }


          public ActionResult Index()
          {
               GetUserData();

               var trainersList = _trainers.GetTrainersList();
               List<Trainer> trainers = new List<Trainer>();

               foreach (var trainer in trainersList)
               {
                    trainers.Add(new Trainer
                    {
                         Id = trainer.Id,
                         Name = trainer.Name,
                         ImageUrl = trainer.ImageUrl,
                         Age = trainer.Age,
                         Bio = trainer.Bio,
                         Number = trainer.Number,
                         Specialization = trainer.Specialization,
                         Availability = trainer.Availability,
                         Price = trainer.Price
                    });
               }


               return View(trainers);
          }

          public ActionResult Details(int id)
          {
               GetUserData();
               ViewBag.Id = id;
               var trainers = _trainers.GetSingleTrainer(id);
               var trainer = new Trainer
               {
                    Id = trainers.Id,
                    Name = trainers.Name,
                    ImageUrl = trainers.ImageUrl,
                    Age = trainers.Age,
                    Bio = trainers.Bio,
                    Number = trainers.Number,
                    Specialization = trainers.Specialization,
                    Availability = trainers.Availability,
                    Price = trainers.Price
               };
               return View(trainer);
          }
          public ActionResult Edit(int id)
          {
               GetUserData();
               GetUserId();
               GetUserLevel();
               int userId = Convert.ToInt32(ViewBag.UserId);
               if (_sessions.GetIdTrainer(userId) == id)
               {
                    var trainer = _trainers.GetSingleTrainer(id);
                    if (trainer != null)
                    {
                         var trainerData = new Trainer
                         {
                              Id = trainer.Id,
                              Name = trainer.Name,
                              ImageUrl = trainer.ImageUrl,
                              Age = trainer.Age,
                              Bio = trainer.Bio,
                              Number = trainer.Number,
                              Specialization = trainer.Specialization,
                              Availability = trainer.Availability,
                              Price = trainer.Price
                         };
                         return View(trainerData);
                    }
                    else
                         return RedirectToAction("Index", "Error");

               }
               return RedirectToAction("Index", "Error");
          }
          [HttpPost]
          [ValidateAntiForgeryToken]
          public ActionResult Edit(Trainer trainer)
          {
               TrainersUDbTable data = new TrainersUDbTable()
               {
                    Id = trainer.Id,
                    Name = trainer.Name,
                    ImageUrl = trainer.ImageUrl,
                    Age = trainer.Age,
                    Bio = trainer.Bio,
                    Number = trainer.Number,
                    Specialization = trainer.Specialization,
                    Availability = trainer.Availability,
                    Price = trainer.Price

               };

               var subscriptionCreate = _trainers.UpdateTrainer(data);
               if (!subscriptionCreate.Status)
               {
                    ModelState.AddModelError("", subscriptionCreate.StatusMsg);
                    return RedirectToAction("Index", "Subscription");

               }
               else
               {
                    return RedirectToAction("Index", "Home");
               }
          }
     }
}

eUseControl.Web/Views/Order/Index.cshtml
@model eUseControl.Web.Models.OrderModel

@{
     ViewBag.Title = "Index";
}
<style>
     /* Custom styles for the carousel container */
     #carousel {
          width: 100%;
     }

     /* Custom styles for the carousel items */
     .owl-carousel .item {
          background-color: #f7f7f7;
          padding: 20px;
          text-align: center;
          border-radius: 5px;
          box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
          transition: all 0.3s ease;
     }

          /* Custom styles for the active item */
          .owl-carousel .item.active {
               transform: scale(1.1);
          }

          /* Custom styles for item content */
          .owl-carousel .item img {
               max-width: 100%;
               height: auto;
               margin-bottom: 15px;
               border-radius: 50%;
          }

          .owl-carousel .item h3 {
               font-size: 20px;
               margin-bottom: 10px;
               color: #333;
          }

          .owl-carousel .item p {
               font-size: 14px;
               color: #777;
               line-height: 1.5;
          }
</style>
<section class="site-section">
     <div class="row justify-content-center text-center mb-5">
          <div class="col-md-8  section-heading">
               <h2 class="heading mb-3">Choose one of Subscriptions</h2>
          </div>
     </div>
     <div id="carousel1" class="owl-carousel nonloop-block-14 block-14">
          @foreach (var item in Model.OrderData.Subscriptions)
          {
               <div class="ftco-feature-1">
                    <div class="row justify-content-center">
                         <div class="card rounded-0 px-4 py-5 ">
                              <img src="@item.ImageUrl" alt="Item Image">
                              <div class="item">
                                   <h3>@item.Id</h3>
                              </div>
                              <p></p>
                              <h2><a>@Html.DisplayFor(modelItem => item.Name)</a></h2>

                              <a href="@Url.Action("Details", "Subscription", new { id = item.Id })" class="btn custom-btn bg-color mt-3" data-aos-delay="300"><center>Details</center></a>
                         </div>

                    </div>
               </div>
          }
     </div>
     <div class="row justify-content-center text-center mb-5">
          <div class="col-md-8  section-heading">
               <h2 class="heading mb-3">Choose one of each Trainers</h2>
          </div>
     </div>
     <div id="carousel2" class="owl-carousel nonloop-block-14 block-14">
          <div class="ftco-feature-1">
               <div class="row justify-content-center">
                    <div class="card rounded-0 px-4 py-5 ">
                         <img src="/assets/images/No-Trainer.jpg" alt="Item Image">
                         <div class="item">
                              <h3>0</h3>
                         </div>
                         <p></p>
                         <h3>Without Trainer</h3>

                    </div>
               </div>
          </div>
          @foreach (var item in Model.OrderData.Trainers)
          {
               <div class="ftco-feature-1">
                    <div class="row justify-content-center">
                         <div class="card rounded-0 px-4 py-5 ">
                              <img src="@item.ImageUrl" alt="Item Image">
                              <div class="item">
                                   <h3>@item.Id</h3>
                              </div>
                              <p></p>
                              <p class="position">Trainer</p>
                              <h3>@item.Name</h3>
                              <p class="position">Specialization</p>
                              @item.Specialization
                              <p class="position">Price per Month</p>
                              @item.Price
                         </div>
                         <a href="@Url.Action("Details", "Trainers", new { id = item.Id })" class="btn custom-btn bg-color mt-3" data-aos-delay="300"><center>Details</center></a>
                    </div>
               </div>
          }
     </div>
     <div class="row justify-content-center text-center mb-5">
          <div class="col-md-8  section-heading">
               <h2 class="heading mb-3">Choose one of Subscription Durations</h2>
          </div>
     </div>
     <div id="carousel3" class="owl-carousel nonloop-block-14 block-14">
          @foreach (var item in Model.OrderData.SubscriptionDurations)
          {
               <div class="ftco-feature-1">
                    <div class="row justify-content-center">
                         <div class="card rounded-0 px-4 py-5 ">
                              <div class="item">
                                   <h3>@item.Id </h3>
                              </div>
                              <p></p>
                              <h2>@item.Name</h2>
                              <p>Luni : @item.Months</p>
                              <p>Reducere: @item.Discount %</p>
                         </div>
                    </div>
               </div>
          }
     </div>

     @using (Html.BeginForm())
     {
          @Html.AntiForgeryToken()

          <div class="form-group text-center">
               <div class="btn btn-outline-black py-3 px-5">
                    <input type="submit" value="Buy Subscripition" class="btn btn-default" />
               </div>
          </div>

          <script>
               $(document).ready(function () {
                    var carousels = [$("#carousel1"), $("#carousel2"), $("#carousel3")];
                    var selectedTitles = ["#selected-title1", "#selected-title2", "#selected-title3"];

                    carousels.forEach(function (carousel, index) {
                         carousel.owlCarousel({
                              items: 5,
                              center: true,
                              nav: true,
                              dots: false,
                              responsive: {
                                   0: {
                                        items: 1
                                   },
                                   600: {
                                        items: 3
                                   },
                                   1000: {
                                        items: 5
                                   }
                              },
                              onInitialized: function (event) {
                                   updateSelectedText(event, index);
                              },
                              onTranslated: function (event) {
                                   updateSelectedText(event, index);
                              }
                         });
                    });

                    function updateSelectedText(event, index) {
                         var currentItem = carousels[index].find(".owl-item.center .item h3");
                         var selectedText = currentItem.text();
                         $(selectedTitles[index]).text(selectedText);

                         // Set the selected title to the hidden field value
                         if (index === 0) {
                              // Set the selected title from Carousel 1 to the SubscriptionId hidden field
                              var selectedTitle1 = selectedText;
                              $("#SubscriptionId").val(selectedTitle1);
                         } else if (index === 1) {
                              // Set the selected title from Carousel 2 to the TrainerId hidden field
                              var selectedTitle2 = selectedText;
                              $("#TrainerId").val(selectedTitle2);
                         } else if (index === 2) {
                              // Set the selected title from Carousel 3 to the SubscriptionDurationId hidden field
                              var selectedTitle3 = selectedText;
                              $("#SubscriptionDurationId").val(selectedTitle3);
                         }
                    }
               });
          </script>

          @Html.HiddenFor(model => model.Orders.SubscriptionId, new { id = "SubscriptionId" })
          @Html.HiddenFor(model => model.Orders.TrainerId, new { id = "TrainerId" })
          @Html.HiddenFor(model => model.Orders.SubscriptionDurationId, new { id = "SubscriptionDurationId" })
     }
</section>