eUseControl.Web/Models/Feedback.cs
using System.ComponentModel.DataAnnotations;

namespace eUseControl.Web.Models
{
    public class Feedback
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        [Required]
        public string Email { get; set; }
        [Required]
        [StringLength(30, MinimumLength = 20)]
        public string Subject { get; set; }
        [Required]
        [StringLength(200, MinimumLength = 30)]
        public string Message { get; set; }

    }
}

eUseControl.Web/Controllers/FeedbackController.cs
using AutoMapper;
using System;
using System.Web.Mvc;
using eUseControl.Domain.Entities.Feedback;
using eUseControl.BusinessLogic.DBModel;
using eUseControl.Web.Filters;
using System.Linq;
using eUseControl.BusinessLogic.BL;
using eUseControl.BusinessLogic.Interfaces;

namespace eUseControl.Web.Controllers
{
     public class FeedbackController : BaseController
     {
          private readonly IFeedback _feedbackRepository;

          public FeedbackController()
          {
               var bl = new BussinesLogic();
               _feedbackRepository = bl.GetFeedbackBl();
          }

          // GET: /Feedback/Index
          public ActionResult Index()
          {
               GetUserData();
               return View();
          }

          // POST: /Feedback/Index
          [HttpPost]
          [ValidateAntiForgeryToken]
          public ActionResult Index(FeedbackModel model)
          {
               GetUserData();
               if (ModelState.IsValid)
               {
                    // Assign the current datetime if not provided by the user
                    if (model.Time == default(DateTime))
                    {
                         model.Time = DateTime.UtcNow; // Assign the current UTC datetime
                    }

                    // Save the feedback to the database
                    var feedbackEntity = MapFeedbackModelToEntity(model);
                    _feedbackRepository.SaveFeedback(feedbackEntity);

                    return RedirectToAction("ThankYou");
               }

               return View();
          }

          // GET: /Feedback/ThankYou
          public ActionResult ThankYou()
          {
               GetUserData();
               return View();
          }

          // GET: /Feedback/FeedbackList
          [AdminMod]
          public ActionResult FeedbackList()
          {
               GetUserData();
               var feedbacks = _feedbackRepository.GetFeedback();
               return View(feedbacks);
          }

          // POST: /Feedback/DeleteFeedback
          [HttpPost]
          [AdminMod]
          [ValidateAntiForgeryToken]
          public ActionResult DeleteFeedback(int id)
          {
               GetUserData();
               _feedbackRepository.DeleteFeedback(id);
               return RedirectToAction("FeedbackList");
          }

          private FeedbackUDbTable MapFeedbackModelToEntity(FeedbackModel model)
          {
               GetUserData();
               var config = new MapperConfiguration(cfg =>
               {
                    cfg.CreateMap<FeedbackModel, FeedbackUDbTable>();
               });

               IMapper mapper = config.CreateMapper();
               var feedbackEntity = mapper.Map<FeedbackUDbTable>(model);

               return feedbackEntity;
          }
     }
}

eUseControl.Web/Views/Feedback/FeedbackList.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "FeedbackList";
}
<style>
    .long-text {
        max-width: 800px; /* Adjust the value as needed */
        word-wrap: break-word;
        overflow-wrap: break-word; /* For compatibility with older browsers */
    }

    table {
        border-collapse: collapse;
        width: 80%;
    }

    th, td {
        border: 1px solid black;
        padding: 8px;
        text-align: left;
    }

    th {
        background-color: #f2f2f2;
    }
</style>

<h2>Feedback List</h2>

<div class="site-section bg-light contact-wrap" id="contact-section">
    <div class="row justify-content-center">
        <table>
            <thead>
                <tr>
                    <th>Id</th>
                    <th>FirstName</th>
                    <th>LastName</th>
                    <th>Email</th>
                    <th>Message</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var feedback in Model)
                {
                    <tr>
                        <td>@feedback.Id</td>
                        <td>@feedback.FirstName</td>
                        <td>@feedback.LastName</td>
                        <td>@feedback.Email</td>
                        <td><p class="long-text">@feedback.Message</p></td>
                        <td>
                            @using (Html.BeginForm("DeleteFeedback", "Feedback", new { id = feedback.Id }, FormMethod.Post))
                            {
                                @Html.AntiForgeryToken()
                                <button type="submit" class="btn btn-danger btn-outline-purple">Delete</button>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

eUseControl.Web/Views/Feedback/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Feedback";
}
@model eUseControl.Web.Models.Feedback
<div class="site-section bg-light contact-wrap" id="contact-section">
    <div class="container">

        <div class="row justify-content-center text-center mb-5">
            <div class="col-md-8  section-heading">
                <span class="subheading">Get In Touch</span>
                <h2 class="heading mb-3">Contact Us</h2>
            </div>
        </div>

        <div class="row justify-content-center">
            <div class="col-md-7">
                <form method="post" data-aos="fade">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()
                        <div class="form-group row">
                            <div class="col-md-6 mb-3 mb-lg-0">
                                @Html.TextBoxFor(m => m.FirstName, new
                                {
                                     type = "text",
                                     placeholder = "FirstName",
                                     title = "FirstName",
                                     value = "",
                                     name = "FirstName",
                                     id = "FirstName",
                                     @class = "form-control"
                                })
                                @Html.ValidationMessageFor(m => m.FirstName, "", new { @class = "validation-error" })
                            </div>
                            <div class="col-md-6">
                                @Html.TextBoxFor(m => m.LastName, new
                                {
                                     type = "text",
                                     placeholder = "LastName",
                                     title = "LastName",
                                     value = "",
                                     name = "LastName",
                                     id = "LastName",
                                     @class = "form-control"
                                })
                                @Html.ValidationMessageFor(m => m.LastName, "", new { @class = "validation-error" })
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-md-12">
                                @Html.TextBoxFor(m => m.Subject, new
                                {
                                     type = "text",
                                     placeholder = "Subject",
                                     title = "Subject",
                                     value = "",
                                     name = "Subject",
                                     id = "Subject",
                                     @class = "form-control"
                                })
                                @Html.ValidationMessageFor(m => m.Subject, "", new { @class = "validation-error" })

                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-md-12">
                                @Html.TextBoxFor(m => m.Email, new
                                {
                                     type = "text",
                                     placeholder = "Email",
                                     title = "Email",
                                     value = "",
                                     name = "Email",
                                     id = "Email",
                                     @class = "form-control"
                                })
                                @Html.ValidationMessageFor(m => m.Email, "", new { @class = "validation-error" })

                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-md-12">
                                @Html.TextAreaFor(m => m.Message, new
                                {
                                     @class = "form-control",
                                     @cols = "30",
                                     @rows = "10",
                                     @placeholder = "Enter Your Message"
                                })
                                @Html.ValidationMessageFor(m => m.Message, "", new { @class = "validation-error" })

                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-md-6">
                                <input type="submit" class="btn btn-primary py-3 px-5 btn-block" value="Send Message">
                            </div>
                        </div>
                    }
                </form>
            </div>
        </div>
    </div>
</div>

eUseControl.Web/Views/Feedback/ThankYou.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "ThankYou";
}
<div class="site-section bg-light contact-wrap" id="contact-section">
    <div class="container text-center">
        <h2>Thanks for your Feedback</h2>
        <p>Your feedback has been submitted successfully.</p>
        <a class="btn btn-default" href="@Url.Action("Index", "Home")">Home</a>
    </div>
</div>