eUseControl.Web/Controllers/LogoutController.cs
using System;
using System.Linq;
using System.Web.Mvc;

namespace eUseControl.Web.Controllers
{
     public class LogoutController : BaseController
     {
          // GET: Logout
          public ActionResult Index()
          {

               System.Web.HttpContext.Current.Session.Clear();
               if (ControllerContext.HttpContext.Request.Cookies.AllKeys.Contains("X-KEY"))
               {
                    var cookie = ControllerContext.HttpContext.Request.Cookies["X-KEY"];
                    if (cookie != null)
                    {
                         cookie.Expires = DateTime.Now.AddDays(-1);
                         ControllerContext.HttpContext.Response.Cookies.Add(cookie);
                    }
               }
               System.Web.HttpContext.Current.Session["LoginStatus"] = "logout";
               return RedirectToAction("Index", "Home");
          }
     }
}

eUseControl.Web/Controllers/OrderController.cs
using System;
using System.Web.Mvc;
using eUseControl.BusinessLogic.BL;
using eUseControl.BusinessLogic.Interfaces;
using eUseControl.Domain.Entities.Order;
using eUseControl.Domain.Entities.Subscription;
using eUseControl.Web.Models;

namespace eUseControl.Web.Controllers
{
     public class OrderController : BaseController
     {
          private readonly ISubscription _subscription;
          private readonly ITrainer _trainers;
          private readonly ISubscriptionDuration _details;
          private readonly IOrder _order;
          public OrderController()
          {
               var bl = new BussinesLogic();
               _subscription = bl.GetSubscriptionBl();
               _trainers = bl.GetTrainerBl();
               _details =bl.GetsSubscriptionDurationBl();
               _order = bl.GetOrderBl();
          }
          public ActionResult Index()
          {
               GetUserData();

               var subscriptions = _subscription.GetSubscriptionList();
               var trainers = _trainers.GetTrainersList();
               var details = _details.GetAllSubscriptionDuration();
               OrderModel data = new OrderModel();
               foreach (var item in subscriptions)
                    data.OrderData.Subscriptions.Add(new SubscriptionData
                    {
                         Id = item.Id,
                         Name = item.Name,
                         Description = item.Description,
                         Price = item.Price,
                         ImageUrl = item.ImageUrl
                    });
               foreach (var item in trainers)
                    data.OrderData.Trainers.Add(new Trainer
                    {
                         Id = item.Id,
                         Name = item.Name,
                         ImageUrl = item.ImageUrl,
                         Age = item.Age,
                         Bio = item.Bio,
                         Number = item.Number,
                         Specialization = item.Specialization,
                         Availability = item.Availability,
                         Price = item.Price
                    });
               foreach (var item in details)
                    data.OrderData.SubscriptionDurations.Add(new SubscriptionDuration()
                    {

                         Id = item.Id,
                         Name = item.Name,
                         Months = item.Months,
                         Discount = item.Discount
                    });

               return View(data);

          }


          [HttpPost]
          public ActionResult Index(OrderModel order)
          {
               GetUserData();
               var data = new OrderDbTable()
               {
                    UserId = ViewBag.UserId,
                    UserName = ViewBag.Username,
                    SubscriptionId = order.Orders.SubscriptionId,
                    TrainerId = order.Orders.TrainerId,
                    SubscriptionDurationId = order.Orders.SubscriptionDurationId,
                    PurchaseDate = DateTime.Now,
                    IsValid = true

               };
               _order.CreateOrder(data);
               return RedirectToAction("UserProfile", "Profile");
          }
     }
}

eUseControl.Web/Controllers/SignUpController.cs
using AutoMapper;
using eUseControl.BusinessLogic.Interfaces;
using eUseControl.BusinessLogic.BL;
using eUseControl.Domain.Entities.User;
using eUseControl.Web.Models;
using System;
using System.Web.Mvc;
using eUseControl.Domain.Enums;
using System.Web;

namespace eUseControl.Web.Controllers
{
     public class SignUpController : BaseController
     {
          private new readonly ISession _session;

          public SignUpController()
          {
               var bl = new BussinesLogic();
               _session = bl.GetSessionBl();

          }

          // GET: Register
          public ActionResult Index()
          {

               return View();
          }

          [HttpPost]
          [ValidateAntiForgeryToken]
          public ActionResult Index(UserSignUp register)
          {
               if (ModelState.IsValid)
               {
                    var config = new MapperConfiguration(cfg => {
                         cfg.CreateMap<UserSignUp, URegisterData>();
                    });
                    IMapper mapper = config.CreateMapper();
                    var data = mapper.Map<URegisterData>(register);

                    data.LoginIp = Request.UserHostAddress;
                    data.LoginDateTime = DateTime.Now;
                    if (register.IsTrainer)
                    {
                         data.Level = URole.Trainer;
                         var bl = new BussinesLogic();
                         var trainer = bl.GetTrainerBl();
                         int trainerId = trainer.TrainerCreate();
                         data.TrainerId = trainerId;

                    }
                    else
                    {
                         data.Level = URole.User;
                         data.TrainerId = null;
                    }

                    var userRegister = _session.UserRegister(data);
                    if (userRegister.Status)
                    {
                         ULoginData data0 = new ULoginData
                         {
                              Credential = register.Username,
                              Password = register.Password,
                              LoginIp = Request.UserHostAddress,
                              LoginDateTime = DateTime.Now,
                         };
                         var userLogin = _session.UserLogin(data0);
                         if (userLogin.Status)
                         {
                              HttpCookie cookie = _session.GenCookie(data0.Credential);
                              ControllerContext.HttpContext.Response.Cookies.Add(cookie);
                         }
                         else
                         {
                              ModelState.AddModelError("", userLogin.StatusMsg);

                         }
                    }
                    else
                    {
                         ModelState.AddModelError("", userRegister.StatusMsg);
                    }
                    if (register.IsTrainer)
                    {
                         return RedirectToAction("Edit", "Trainers", new { id = data.TrainerId });
                    }
                    else
                    {
                         return RedirectToAction("Index", "Home");
                    }
               }
               return View();
          }
     }
}

eUseControl.Web/Views/Shared/_Footer.cshtml
@{
    ViewBag.Title = "_Footer";
}
<footer class="footer-section bg-dark">
    <div class="container">
        <div class="row">
            <div class="col-md-5">
                <h3>About Us</h3>
                <p>
                    Welcome to WORKOUT.!

                    At WORKOUT., we believe that fitness is not just a goal, but a way of life. We are dedicated to providing a motivating and inclusive environment for individuals of all fitness levels.
                </p>
            </div>
            <div class="col-md-4">
                <h3>Contact</h3>
                <ul class="contact-info">
                    <li><i class="fa fa-envelope"></i> workout@gmail.com</li>
                    <li><i class="fa fa-phone"></i> +373 68123456</li>
                    <li><i class="fa fa-map-marker"></i> Str. Studenților, 7, Chișinău, Chişinău</li>
                </ul>
            </div>
            <div class="col-md-2">
                <h3>Follow Us</h3>
                <!-- Section: Social media -->
                <section>
                    <!-- Facebook -->
                    <a class="btn text-white btn-floating m-1" style="background-color: #3b5998; border-radius: 50%;" href="#!" role="button">
                        <i class="fab fa-facebook-f"></i>
                    </a>

                    <!-- Twitter -->
                    <a class="btn text-white btn-floating m-1" style="background-color: #55acee; border-radius: 50%;" href="#!" role="button">
                        <i class="fab fa-twitter"></i>
                    </a>

                    <!-- Google -->
                    <a class="btn text-white btn-floating m-1" style="background-color: #dd4b39; border-radius: 50%;" href="#!" role="button">
                        <i class="fab fa-google"></i>
                    </a>

                    <!-- Instagram -->
                    <a class="btn text-white btn-floating m-1" style="background-color: #ac2bac; border-radius: 50%;" href="#!" role="button">
                        <i class="fab fa-instagram"></i>
                    </a>

                    <!-- Linkedin -->
                    <a class="btn text-white btn-floating m-1" style="background-color: #0082ca; border-radius: 50%;" href="#!" role="button">
                        <i class="fab fa-linkedin-in"></i>
                    </a>

                    <!-- Github -->
                    <a class="btn text-white btn-floating m-1" style="background-color: #333333; border-radius: 50%;" href="#!" role="button">
                        <i class="fab fa-github"></i>
                    </a>
                </section>

                <!-- Section: Social media -->
            </div>
        </div>
    </div>
</footer>

eUseControl.Web/Views/Shared/_Layout.cshtml
@using System.Web.Optimization

<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>eUse System | @ViewBag.Title</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900" rel="stylesheet" type="text/css">

    @Styles.Render("~/bundles/aos/css")
    @Styles.Render("~/bundles/bootstrap-datepicker/css")
    @Styles.Render("~/bundles/bootstrap.min/css")
    @Styles.Render("~/bundles/jquery-ui/css")
    @Styles.Render("~/bundles/jquery.fancybox.min/css")
    @Styles.Render("~/bundles/jquery.mb.YTPlayer.min/css")
    @Styles.Render("~/bundles/magnific-popup/css")
    @Styles.Render("~/bundles/mediaelementplayer/css")
    @Styles.Render("~/bundles/owl.carousel.min/css")
    @Styles.Render("~/bundles/owl.theme.default.min/css")
    @Styles.Render("~/bundles/style/css")
    @Styles.Render("~/bundles/validation/css")

    @if (IsSectionDefined("Styles"))
    {@RenderSection("Styles", required: false)}

</head>
<body>
    <!-- Navigation -->
    @Html.Partial("_Navigation")
    <!-- Main view -->
    @RenderBody()
    @Html.Partial("_Footer")

    @Scripts.Render("~/bundles/aos/js")
    @Scripts.Render("~/bundles/bootstrap-datepicker.min/js")
    @Scripts.Render("~/bundles/bootstrap.min/js")
    @Scripts.Render("~/bundles/jquery-3.3.1.min/js")
    @Scripts.Render("~/bundles/jquery-migrate-3.0.1.min/js")
    @Scripts.Render("~/bundles/jquery-ui/js")
    @Scripts.Render("~/bundles/jquery.countdown.min/js")
    @Scripts.Render("~/bundles/jquery.easing.1.3/js")
    @Scripts.Render("~/bundles/jquery.fancybox.min/js")
    @Scripts.Render("~/bundles/jquery.magnific-popup.min/js")
    @Scripts.Render("~/bundles/jquery.mb.YTPlayer.min/js")
    @Scripts.Render("~/bundles/jquery.stellar.min/js")
    @Scripts.Render("~/bundles/jquery.sticky/js")
    @Scripts.Render("~/bundles/main/js")
    @Scripts.Render("~/bundles/mediaelement-and-player.min/js")
    @Scripts.Render("~/bundles/owl.carousel.min/js")
    @Scripts.Render("~/bundles/popper.min/js")
    @Scripts.Render("~/bundles/slick.min/js")
    @Scripts.Render("~/bundles/typed/js")


    <!-- Handler for local scripts -->
    @RenderSection("scripts", required: false)
</body>
</html>

eUseControl.Web/Views/Shared/_Navigation.cshtml
@{
    ViewBag.Title = "_Navigation";
}
<header class="site-navbar py-4 js-sticky-header site-navbar-target" role="banner">

    <div class="container-fluid">
        <div class="d-flex align-items-center">
            <div class="site-logo"><a href="@Url.Action("Index","Home")">Workout<span>.</span> </a></div>
            <div class="ml-auto">
                <nav class="site-navigation position-relative text-right" role="navigation">
                     <ul class="site-menu main-menu js-clone-nav mr-auto d-none d-lg-block">
                          <li><a href="@Url.Action("Index","Home")" class="nav-link">Home</a></li>
                          <li><a href="@Url.Action("Index","Subscription")" class="nav-link">Subscriptions</a></li>
                          <li><a href="@Url.Action("Index","Trainers")" class="nav-link">Trainers</a></li>
                          <li><a href="@Url.Action("Index","Order")" class="nav-link">Orders</a></li>
                          @{
                               if (ViewBag.UserLevel == "Admin")
                               {
                                    <li><a href="@Url.Action("FeedbackList", "Feedback")" class="nav-link">Feedback List</a></li>
                               }
                               else
                               {
                                    <li><a href="@Url.Action("Index", "Feedback")" class="nav-link">Feedback</a></li>

                               }
                          }
                               @if ((string)System.Web.HttpContext.Current.Session["LoginStatus"] == "login")
                          {
                               <li><a href="@Url.Action("Index","Profile")" class="btn-bordered-purple">User: @ViewBag.Username</a></li>

                               @*<li><a href="@Url.Action("Edit","Trainers",new { id = ViewBag.UserId })" class="nav-link">Edit Profile</a></li>*@
                               <li><a href="@Url.Action("Index","Logout")" class="nav-link">LogOut</a></li>
                          }
                          else
                          {
                               <li><a href="@Url.Action("Index","SignUp")" class="nav-link">SignUp</a></li>
                               <li><a href="@Url.Action("Index","LogIn")" class="nav-link">LogIn</a></li>
                          }
                     </ul>
                </nav>
                <a href="#" class="d-inline-block d-lg-none site-menu-toggle js-menu-toggle float-right"><span class="icon-menu h3"></span></a>
            </div>

        </div>
    </div>
</header>